### ISSUE TITLE
When I Compile the solution by x86,It can't connect,why

### ISSUE THREAD

**Issue by fjwgrace** [tetherscript/hvdk#2]
When I Compile the solution by x86,It can't connect,why

**Comment by tetherscript** [comment]
Hi,

 
I’m not sure why, but I haven’t tried  is on an x86 compilation either.  We do have 32-bit Delphi apps running and accessing the 64-bit drivers just fine, so this should be possible.  Either way, you’ll need a 64-bit version of Windows to run the drivers.

 
Cheers,

Russ Beuker at Tetherscript helpdesk

**Comment by tetherscript** [comment]
Not sure why it wouldn't compile, and we don't have 32-bit version of the c# sample projects available.  The drivers are 64-bit only, but they can be accessed with 32-bit apps such as our Delphi sample apps.
