### ISSUE TITLE
(keyboard) how to use multiple modifieres ?

### ISSUE THREAD

**Issue by Micke3rd** [tetherscript/hvdk#7]
Hi,
there are keyboard layouts which demand 2 modifiers to access chars
e.g. "en-UK" : ctrl + alt + 4 = €
e.g. "de" : ctrl + alt + 8 = [
or the well known:  ctrl + alt + del

With a mechanical keyboard we can combine all keys with each other.
With HVDK too, except if it comes to modifiers.
HVDK differentiates between modifiers and not modifier keys, what is different to the hut1_12v2.pdf specification. There modifiers are just keys with usage IDs from 224 to 231.

HVDK's function Send
```
void Send(byte Modifier, byte Padding, byte Key0, byte Key1, byte Key2, byte Key3, byte Key4, byte Key5)
```
denies the usage of more than 1 modifier. Two combined calls of Send with different modifiers don't help too.
If modifiers wouldn't be handled as different key type anymore, the function Send could be shrinked in my opinion to
```
void Send(byte Key0)
```
Because padding is always 0 and the usage for e.g. "ctrl + alt + 4 = €" would be:

1. Send( GetKeyFor("ctrl"))
// with no interrupt
2. Send( GetKeyFor("alt"))
// with no interrupt
3. Send( GetKeyFor("4"))
// interrupt:
4. Send(0, 0, 0, 0, 0, 0, 0, 0);

I simulated this by using scan codes from 224, but HVDK doesn't deliver anything for that range in the current version.

What do you think about?
Do I oversee something ?

**Comment by tetherscript** [comment]
@Micke3rd  This is a good question, and the short answer is that the **byte Modifier** parameter is a bit array of length 8 that contains the state of each of the eight modifier keys.  The least-significant bit is the right-most bit in this byte.

_A modifier modifies how a Key is used. There are eight modifiers, and each modifier represents a bit array position contained in a single byte. 

So if you wanted to press the Left Control Key, you would set bit zero to 1. And later to release it, you would set bit zero to 0. 
00000001

If you have more than one modifier pressed at the same time, like LCTRL-LSHIFT, you just OR the (1 and 2) values together to get 3. 
00000011

A modifier byte value of 255 would  mean all eight modifier keys are pressed.  If no modifiers are pressed, all bits are zero. Here are the modifiers:

    Bit 0 = LCTRL: Left Control Key
    Bit 1 = LSHIFT: Left Shift Key
    Bit 2 = LALT: Left Alt Key
    Bit 3 = LWIN: Left Control Key
    Bit 4 = RCTRL: Right Control Key
    Bit 5 = RSHIFT: Right Shift Key
    Bit 6 = RALT: Right Alt Key
    Bit 7 = RWIN: Right Windows Key_


>>e.g. "en-UK" : ctrl + alt + 4 = €
>>e.g. "de" : ctrl + alt + 8 = [

So to make this work with the German-German keyboard from your question, install the German-German keyboard layout on Windows 10 and select it is the active keyboard layout, then run this (Delphi) code:

    Send(5, 0, 37, 0, 0, 0, 0, 0);   //modifier value is (LCTRL + LALT) = (1 or 4) = 5.  UsageID for '8' is 37.
    sleep(50);
    Send(0, 0, 0, 0, 0, 0, 0, 0);

and for the English-UK keyboard question, install that keyboard layout and use:

    Send(5, 0, 33, 0, 0, 0, 0, 0);   //modifier value is (LCTRL + LALT) = (1 or 4) = 5.  UsageID for '4' is 33.
    sleep(50);
    Send(0, 0, 0, 0, 0, 0, 0, 0);

I just tried this and it works.

Hope that helps!

Russ

**Comment by Micke3rd** [comment]
aaah certainly, didn't realize we are on the bit level here. Thank you.

but then KeyboardUtils
```
		public static byte GetModifierKeyCode(string modifier)
		{
			var i = FModifiers.IndexOf(modifier);
			if (i == -1) { return 0; } else { return (byte)i; };
		}
```
should return  (byte)Math.Pow(2, i);
because actually "GetModifierKeyCode" returns the index, not the KeyCode.

**Comment by tetherscript** [comment]
@Micke3rd Indeed the KeyboardUtils code could be tweaked, but eventually you'll need some kind of 'get the bit position and OR it with the other possible modifiers currently pressed'.  I have tended to leave that code up to dev.
